fastapi:
  dev:
    host: "0.0.0.0"
    port: 8080
  prod:
    host: "127.0.0.1"
    port: 8080

converse_engine:
  provider: "AWS"
  model_id: "anthropic.claude-3-haiku-20240307-v1:0"
  temperature: 0.5
  max_tokens: 2048

content_generation_model:
  provider: "AWS"
  modelId: "anthropic.claude-3-haiku-20240307-v1:0"
  temperature: 0.5
  maxTokens: 512
  
RAG_embedding_model:
  default:
    provider: "Cohere"
    modelId: "cohere.embed-english-v3"
  preferred:
    provider: "Cohere"
    modelId: "cohere.embed-english-v3"

backend_db:
  host: 
    remote: "100.127.0.244"
    ec2: "172.17.0.1" # Docker’s gateway IP
  port: 5432
  database: "xxx"
  user: "xxx"
  password: "xxx" 
  connect_timeout: 7

redis:
  host: "localhost"
  port: 6379
  db: 0
  ttl: 7200