CHAT_ENGINE:
  host:
    darwin: "0.0.0.0"
    windows: "localhost"
    ec2: "0.0.0.0"
  port: 8080

converse_engine:
  provider: "AWS"
  model_id: "anthropic.claude-3-haiku-20240307-v1:0"
  temperature: 0.5
  max_tokens: 2048

content_generation_model:
  default:
    provider: "AWS"
    modelId: "anthropic.claude-3-haiku-20240307-v1:0"
    contextSize: 16384
    maxTokens: 256

RAG_text_generation_model:
  default:
    provider: "AWS"
    modelId: "anthropic.claude-3-5-sonnet-20240620-v1:0"
    contextSize: 200000
    maxTokens: 4096
  preferred:
    provider: "AWS"
    modelId: "anthropic.claude-3-5-sonnet-20240620-v1:0"  
    contextSize: 200000
    maxTokens: 4096
  
RAG_embedding_model:
  default:
    provider: "Cohere"
    modelId: "cohere.embed-english-v3"
  preferred:
    provider: "Cohere"
    modelId: "cohere.embed-english-v3"

BACKEND_DB:
  host: 
    remote: "100.127.0.244"
    ec2: "172.17.0.1" # Docker’s gateway IP
  port: 5432
  database: "app_db"
  user: "app_backend"
  password: "@ppBackendP@ssw0rd" 
  connect_timeout: 7

